#
# VDRSD Configuration File - Node 2
#

node_id=node2
listen_port=9002
storage_path=./node2_live_data
device_path=/dev/vdrsd_node2_unused

# Peer list (format: peer=id:ip:port)
peer=node1:127.0.0.1:9001
